# Generated by Django 3.0.5 on 2022-05-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='address',
        ),
    ]
