# Generated by Django 3.0.5 on 2022-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0002_remove_customer_reg_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(null=True, upload_to='media/')),
                ('desc', models.TextField(null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
