# Generated by Django 3.0.5 on 2022-05-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Catg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('discount', models.IntegerField(null=True)),
                ('active', models.BooleanField()),
                ('catg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewrd_Management_App.Coupon_Catg')),
            ],
        ),
    ]
