# Generated by Django 3.0.5 on 2022-05-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0005_coupon_coupon_catg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
    ]
