# Generated by Django 3.0.5 on 2022-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0008_auto_20220525_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='discount_coupon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
