# Generated by Django 3.2 on 2022-06-17 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewrd_Management_App', '0014_blockchain_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain_admin',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='blockchain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='blockchain_entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='blockchain_status',
            field=models.CharField(default='not active', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='blockchain_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Remark', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('blockchain_count', models.IntegerField(default=0)),
                ('blockchain_entry_count', models.IntegerField(default=0)),
                ('last_status', models.CharField(default='not active', max_length=100)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('count', models.IntegerField(null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewrd_Management_App.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
