# Generated by Django 3.2 on 2022-06-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0019_auto_20220620_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewrd_Management_App.shop_registration'),
        ),
    ]
