# Generated by Django 3.2 on 2022-06-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0020_employee_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_reg',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='phonenumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer_reg',
            name='pin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
