# Generated by Django 3.2 on 2022-06-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0021_auto_20220625_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_reg',
            name='pin',
        ),
    ]
