# Generated by Django 3.2 on 2022-06-25 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewrd_Management_App', '0023_auto_20220625_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain_ledger_encripted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Remark', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('blockchain_count', models.CharField(default=0, max_length=100)),
                ('blockchain_entry_count', models.CharField(default=0, max_length=100)),
                ('last_status', models.CharField(default='not active', max_length=100)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('count', models.IntegerField(null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewrd_Management_App.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
