# Generated by Django 3.2 on 2022-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0024_blockchain_ledger_encripted'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain_admin',
            name='key2',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
    ]
