# Generated by Django 3.2 on 2022-06-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewrd_Management_App', '0025_blockchain_admin_key2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
    ]
